Repository SOPT-all/35-APPJAM-ANDROID-NAPZAKMARKET, pull requests merged in 2025-01, with the labels that each got.

#6 [ADD/#5] PR 템플릿 파일 이동
  .github/pull_request_template.md
Labels: HOTFIX :hammer_and_wrench:, 석준 :melting_face:

#7 [ADD/#3] 프로젝트 패키지 구조 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/napzak/market/NapzakApplication.kt
  app/src/main/java/com/napzak/market/core/common/extension/Context.kt
  app/src/main/java/com/napzak/market/core/common/extension/Modifier.kt
  app/src/main/java/com/napzak/market/core/common/navigation/Route.kt
  app/src/main/java/com/napzak/market/core/common/state/UiState.kt
  app/src/main/java/com/napzak/market/core/common/util/NoRippleInteractionSource.kt
  app/src/main/java/com/napzak/market/core/designsystem/theme/Theme.kt
  app/src/main/java/com/napzak/market/core/network/NetworkModule.kt
  app/src/main/java/com/napzak/market/core/network/RetrofitExtension.kt
  app/src/main/java/com/napzak/market/data/dummy/datasource/DummyDataSource.kt
  app/src/main/java/com/napzak/market/data/dummy/datasourceimpl/DummyDataSourceImpl.kt
  app/src/main/java/com/napzak/market/data/dummy/di/DataSourceModule.kt
  app/src/main/java/com/napzak/market/data/dummy/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/dummy/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/dummy/dto/GetUserListResponse.kt
  app/src/main/java/com/napzak/market/data/dummy/mapper/UserDataMapper.kt
  app/src/main/java/com/napzak/market/data/dummy/repositoryimpl/DummyRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/dummy/service/DummyService.kt
  app/src/main/java/com/napzak/market/domain/dummy/model/DummyUser.kt
  app/src/main/java/com/napzak/market/domain/dummy/repository/DummyRepository.kt
  app/src/main/java/com/napzak/market/presentation/dummy/DummyScreen.kt
  app/src/main/java/com/napzak/market/presentation/dummy/DummyViewModel.kt
  app/src/main/java/com/napzak/market/presentation/dummy/component/DummyUserItem.kt
  app/src/main/java/com/napzak/market/presentation/dummy/navigation/DummyNavigation.kt
  app/src/main/java/com/napzak/market/presentation/dummy/state/DummyUiState.kt
  app/src/main/java/com/napzak/market/presentation/main/MainActivity.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainBottomBar.kt
  gradle/libs.versions.toml
Labels: ADD ➕, FEAT :sparkles:, 석준 :melting_face:

#10 [ADD/#4] 깃허브 CI
  .github/workflows/android_develop.yml
  .gitignore
Labels: ADD ➕, 석준 :melting_face:

#11 [Add/#9] Color 및 Typography 설정
  app/src/main/java/com/napzak/market/core/designsystem/theme/Color.kt
  app/src/main/java/com/napzak/market/core/designsystem/theme/Theme.kt
  app/src/main/java/com/napzak/market/core/designsystem/theme/Type.kt
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_semibold.ttf
Labels: ADD ➕, 종명 :melting_face:

#17 [DOCS/#16] 리드미 작성
  README.md
Labels: DOCS :memo:, 석준 :melting_face:

#20 [UI/#12] 검색창, chip 컴포넌트 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/SelectableChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/type/SelectableChipType.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/textField/SearchBox.kt
  app/src/main/res/drawable/ic_down_chevron_16.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_x_circle_16.xml
  app/src/main/res/values/strings.xml
Labels: 채린 :melting_face:, UI :iphone:

#19 [UI/#13] 탑바, 버튼 컴포넌트 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/button/CommonButton.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/EnableDisableTextButton.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/BackTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CenteredTextTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CloseTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/res/drawable/ic_add_13.xml
  app/src/main/res/drawable/ic_back_24.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/values/strings.xml
Labels: 재원 :melting_face:, UI :iphone:

#18 [UI/#14] 담당 컴포넌트 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/GenreChipButtonGroup.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/RoundedIconButton.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/model/CustomButtonColors.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/BasicChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/RemovableChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/TextChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/model/CustomChipColors.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/NapzakBaseItem.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/NapzakBuyItem.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/NapzakSellItem.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/OnboardingGenreItem.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/text/SingleLineText.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainRegisterDialog.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/main/type/RegisterTab.kt
  app/src/main/res/drawable/ic_buy_28.xml
  app/src/main/res/drawable/ic_chat_select_28.xml
  app/src/main/res/drawable/ic_chat_unselect_28.xml
  app/src/main/res/drawable/ic_checkbox_select_16.xml
  app/src/main/res/drawable/ic_close_18.xml
  app/src/main/res/drawable/ic_heart_select_24.xml
  app/src/main/res/drawable/ic_heart_unselect_24.xml
  app/src/main/res/drawable/ic_home_select_28.xml
  app/src/main/res/drawable/ic_home_unselect_28.xml
  app/src/main/res/drawable/ic_look_select_28.xml
  app/src/main/res/drawable/ic_look_unselect_28.xml
  app/src/main/res/drawable/ic_my_select_28.xml
  app/src/main/res/drawable/ic_my_unselect_28.xml
  app/src/main/res/drawable/ic_register_select_28.xml
  app/src/main/res/drawable/ic_register_unselect_28.xml
  app/src/main/res/drawable/ic_reset_18.xml
  app/src/main/res/drawable/ic_sell_24.xml
  app/src/main/res/values/strings.xml
Labels: 석준 :melting_face:, UI :iphone:

#28 [UI/#23] 온보딩 화면
  app/src/main/java/com/napzak/market/core/designsystem/component/GenreChipButtonGroup.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/CommonButton.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/EnableDisableTextButton.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/OnboardingGenreItem.kt
  app/src/main/java/com/napzak/market/domain/genre/model/Genre.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingScreen.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/component/GradientBox.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/component/OnboardingBottomBar.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/component/OnboardingTopBar.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/state/OnboardingUiState.kt
  app/src/main/res/values/strings.xml
Labels: 석준 :melting_face:, UI :iphone:

#24 [UI/#22] 채팅 화면 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CenteredTextTopBar.kt
  app/src/main/java/com/napzak/market/presentation/chat/component/ChatInfoSection.kt
  app/src/main/java/com/napzak/market/presentation/chat/screen/ChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/screen/ItemChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/type/ChatType.kt
  app/src/main/res/drawable/img_chat_background.xml
  app/src/main/res/drawable/img_chat_ready.xml
  app/src/main/res/values/strings.xml
Labels: 재원 :melting_face:, UI :iphone:

#31 [UI/#27] 검색화면 및 검색결과화면 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/SelectableChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/textField/SearchBox.kt
  app/src/main/java/com/napzak/market/presentation/explore/ExploreRoute.kt
  app/src/main/java/com/napzak/market/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/ExploreFilterGroup.kt
  app/src/main/java/com/napzak/market/presentation/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/state/ExploreUiState.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/ExploreScreenType.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/search/SearchRoute.kt
  app/src/main/java/com/napzak/market/presentation/search/SearchViewModel.kt
  app/src/main/java/com/napzak/market/presentation/search/component/GenreTextChip.kt
  app/src/main/java/com/napzak/market/presentation/search/component/SearchGenreItem.kt
  app/src/main/java/com/napzak/market/presentation/search/component/SearchGenreListSection.kt
  app/src/main/java/com/napzak/market/presentation/search/navigation/SearchNavigation.kt
  app/src/main/java/com/napzak/market/presentation/search/state/SearchUiState.kt
  app/src/main/res/values/strings.xml
Labels: 채린 :melting_face:, UI :iphone:

#33 [UI/#25] 마이페이지 화면 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/button/CommonButton.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/napzak/market/presentation/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/napzak/market/presentation/mypage/state/MyPageUiState.kt
  app/src/main/java/com/napzak/market/presentation/mypage/type/MyPageMenuType.kt
  app/src/main/res/drawable/ic_my_favorite_54.xml
  app/src/main/res/drawable/ic_my_genre_54.xml
  app/src/main/res/drawable/ic_my_history_54.xml
  app/src/main/res/drawable/ic_my_recent_54.xml
  app/src/main/res/drawable/ic_profile_basic_60.xml
  app/src/main/res/values/strings.xml
Labels: 재원 :melting_face:, UI :iphone:

#36 [UI/#15] 등록 뷰 컴포넌트
  app/src/main/java/com/napzak/market/core/common/extension/Modifier.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/BackTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CenteredTextTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CloseTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostOptionCard.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostPriceSelector.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/ProductConditionGridButton.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationGenreButton.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationNumberTextField.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPhotoPicker.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPlainTextField.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPriceTextField.kt
  app/src/main/res/drawable/ic_back_48.xml
  app/src/main/res/drawable/ic_checkbox_selected_20.xml
  app/src/main/res/drawable/ic_checkbox_unselected_20.xml
  app/src/main/res/drawable/ic_close_circle_28.xml
  app/src/main/res/drawable/ic_down_24.xml
  app/src/main/res/drawable/ic_more_18.xml
  app/src/main/res/drawable/ic_photo_28.xml
  app/src/main/res/drawable/ic_up_24.xml
  app/src/main/res/values/strings.xml
Labels: 종명 :melting_face:, UI :iphone:

#34 [UI/#29] 홈화면 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/indicator/PageIndicator.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/NapzakLogoTopBar.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeViewModel.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeBannerPager.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeItemMapper.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeItemRow.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/napzak/market/presentation/home/state/HomeUiState.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/res/drawable/img_banner_home1.png
  app/src/main/res/drawable/img_banner_home2.png
  app/src/main/res/drawable/img_home_popular.png
  app/src/main/res/drawable/img_home_recommend.png
  app/src/main/res/drawable/img_home_search.png
  app/src/main/res/drawable/img_logo_text.png
  app/src/main/res/values/strings.xml
Labels: 석준 :melting_face:, UI :iphone:

#41 [FIX/#35] 장르 칩 수정
  app/src/main/java/com/napzak/market/core/designsystem/component/GenreChipButtonGroup.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/button/RoundedIconButton.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingScreen.kt
Labels: FIX :hammer:, 석준 :melting_face:

#40 [UI/#32] 탐색탭 바텀시트 구현완료!
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/SelectableChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/GenreSearchItem.kt
  app/src/main/java/com/napzak/market/presentation/explore/ExploreRoute.kt
  app/src/main/java/com/napzak/market/presentation/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/presentation/explore/bottomSheet/SortBottomSheet.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/ExploreBottomSheetScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/ExploreFilterGroup.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/GenreSearchNoticeSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/component/TradeTypeTab.kt
  app/src/main/java/com/napzak/market/presentation/explore/state/ExploreBottomSheetState.kt
  app/src/main/java/com/napzak/market/presentation/explore/state/ExploreUiState.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/ExploreBottomSheetType.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/ExploreScreenType.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/SortType.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/TradeType.kt
  app/src/main/java/com/napzak/market/presentation/search/component/SearchGenreListSection.kt
  app/src/main/res/drawable/ic_check_24.xml
  app/src/main/res/values/strings.xml
Labels: 채린 :melting_face:, UI :iphone:

#43 [UI/#37] 상세페이지 화면 구현
  app/src/main/java/com/napzak/market/core/designsystem/component/snackbar/CommonSnackBar.kt
  app/src/main/java/com/napzak/market/core/type/ProductConditionType.kt
  app/src/main/java/com/napzak/market/presentation/chat/navigation/ChatNavigation.kt
  app/src/main/java/com/napzak/market/presentation/chat/screen/ChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/screen/ItemChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageViewModel.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/component/ProductInfoSection.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/navigation/DetailPageNavigation.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/state/DetailPageUiState.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/res/drawable/ic_heart_24.xml
  app/src/main/res/drawable/ic_heart_sm_16.xml
  app/src/main/res/drawable/ic_heart_toast_18.xml
  app/src/main/res/drawable/ic_view_16.xml
  app/src/main/res/drawable/img_chat_background.png
  app/src/main/res/drawable/img_chat_background.xml
  app/src/main/res/drawable/img_chat_ready.png
  app/src/main/res/drawable/img_chat_ready.xml
  app/src/main/res/values/strings.xml
Labels: 재원 :melting_face:, UI :iphone:

#48 [FIX/#47] 온보딩 그라디엔트 추가
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingScreen.kt
Labels: FIX :hammer:, 석준 :melting_face:

#56 [Refactor/#52] 파일 변경 및 폴더구조 변경
  app/src/main/java/com/napzak/market/core/designsystem/component/item/GenreSearchItem.kt
  app/src/main/java/com/napzak/market/core/type/BottomSheetType.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreRoute.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/bottomSheet/SortBottomSheet.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ExploreBottomSheetScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ExploreFilterGroup.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/GenreSearchNoticeSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/TradeTypeTab.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/state/ExploreBottomSheetState.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/state/ExploreUiState.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/type/ExploreScreenType.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/type/TradeType.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchRoute.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/component/GenreTextChip.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/component/SearchGenreListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/navigation/SearchNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/state/SearchUiState.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/ExploreBottomSheetType.kt
  app/src/main/java/com/napzak/market/presentation/explore/type/SortType.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/state/HomeUiState.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoViewModel.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketInfoBottomSheetScreen.kt
Labels: REFACTOR :recycle:, 채린 :melting_face:

#54 [FEAT/#53] 채팅화면 탐색 연결
  app/src/main/java/com/napzak/market/core/designsystem/component/image/EmptyImage.kt
  app/src/main/java/com/napzak/market/presentation/chat/chat/ChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/chat/navigation/ChatNavigation.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/ItemChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/component/ChatInfoSection.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/navigation/ItemChatNavigation.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/type/ChatType.kt
  app/src/main/java/com/napzak/market/presentation/chat/screen/ChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/type/ChatType.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/type/MainTab.kt
  app/src/main/java/com/napzak/market/presentation/prepare/PrepareScreen.kt
  app/src/main/java/com/napzak/market/presentation/prepare/navigation/chatNavigation.kt
  app/src/main/res/drawable/img_chat_ready.png
  app/src/main/res/drawable/img_ready.png
Labels: FIX :hammer:, 석준 :melting_face:

#58 [FIX/#57] TradeType 의존성 수정
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/SortBottomSheet.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ExploreBottomSheetScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/type/TradeType.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/state/HomeUiState.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketInfoBottomSheetScreen.kt
Labels: FIX :hammer:, 석준 :melting_face:

#59 [FIX/#55] 바텀바 스택 수정
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
Labels: FIX :hammer:, 석준 :melting_face:

#60 [FIX/#49] 탐색<->검색 네비게이션 수정
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
Labels: FIX :hammer:, 채린 :melting_face:

#64 [FIX/#62] 탐색탭 내 오류 수정
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/textField/SearchBox.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ExploreFilterGroup.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
Labels: FIX :hammer:, 채린 :melting_face:

#66 [FEAT/#61] 상세페이지 이동 로직
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageViewModel.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/navigation/DetailPageNavigation.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/navigation/ExploreNavigation.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/navigation/MarketInfoNavigation.kt
Labels: FEAT :sparkles:, 석준 :melting_face:

#67 [FEAT/#63] 토큰 관리 로직 추가
  app/src/main/java/com/napzak/market/core/local/DataStoreModule.kt
  app/src/main/java/com/napzak/market/core/local/TokenDataStore.kt
  app/src/main/java/com/napzak/market/core/network/AuthInterceptor.kt
  app/src/main/java/com/napzak/market/core/network/BaseResponse.kt
  app/src/main/java/com/napzak/market/core/network/di/NetworkModule.kt
  app/src/main/java/com/napzak/market/core/network/di/NetworkQualifier.kt
  gradle/libs.versions.toml
Labels: FEAT :sparkles:, 석준 :melting_face:

#72 [ADD/#71] 토큰 및 URL 추가
  app/build.gradle.kts
  app/src/main/java/com/napzak/market/core/local/TokenDataStore.kt
  app/src/main/java/com/napzak/market/core/network/di/NetworkModule.kt
Labels: ADD ➕, 석준 :melting_face:

#74 [FEAT/#69] 홈화면 배너 API
  app/src/main/java/com/napzak/market/core/network/AuthInterceptor.kt
  app/src/main/java/com/napzak/market/core/network/di/NetworkModule.kt
  app/src/main/java/com/napzak/market/data/home/datasource/HomeDataSource.kt
  app/src/main/java/com/napzak/market/data/home/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/home/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomeBannerResponse.kt
  app/src/main/java/com/napzak/market/data/home/mapper/HomeBannerMapper.kt
  app/src/main/java/com/napzak/market/data/home/repositoryImpl/HomeRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/home/service/HomeService.kt
  app/src/main/java/com/napzak/market/domain/home/model/HomeBanner.kt
  app/src/main/java/com/napzak/market/domain/home/repository/HomeRepository.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeViewModel.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeBannerPager.kt
  app/src/main/java/com/napzak/market/presentation/home/state/HomeUiState.kt
Labels: FEAT :sparkles:, 석준 :melting_face:

#82 [FEAT/#80] 장르 검색 Domain 부분 구현
  app/src/main/java/com/napzak/market/data/genre/datasource/GenreDataSource.kt
  app/src/main/java/com/napzak/market/data/genre/di/GenreListMapper.kt
  app/src/main/java/com/napzak/market/data/genre/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/genre/dto/GenreListResponse.kt
  app/src/main/java/com/napzak/market/data/genre/repositoryimpl/GenreRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/genre/service/GenreService.kt
  app/src/main/java/com/napzak/market/domain/genre/model/Genre.kt
  app/src/main/java/com/napzak/market/domain/genre/respository/GenreRepository.kt
Labels: FEAT :sparkles:, 채린 :melting_face:

#65 [UI/#39] 등록 화면 구현
  app/src/main/java/com/napzak/market/core/common/util/NumericVisualTransformation.kt
  app/src/main/java/com/napzak/market/core/type/ProductConditionType.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationGenreSearchScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationViewModel.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostFeeSelector.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostOptionCard.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/ProductConditionGridButton.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationBuyGroup.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationCheckBox.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationGenreButton.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationNumberTextField.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPhotoPicker.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPlainTextField.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationPriceTextField.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationSellGroup.kt
  app/src/main/java/com/napzak/market/presentation/registration/navigation/RegistrationNavigation.kt
  app/src/main/java/com/napzak/market/presentation/registration/state/RegistrationUiState.kt
  app/src/main/java/com/napzak/market/presentation/registration/type/PostFeeType.kt
  app/src/main/java/com/napzak/market/presentation/registration/type/TextInputType.kt
  app/src/main/res/values/strings.xml
Labels: 종명 :melting_face:, UI :iphone:

#81 [FEAT/#75] 홈화면 목록 API 연결
  app/src/main/java/com/napzak/market/core/common/extension/String.kt
  app/src/main/java/com/napzak/market/data/home/datasource/HomeDataSource.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomeBannerResponse.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomeBuyProductResponse.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomePopularProductResponse.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomeRecommendProductResponse.kt
  app/src/main/java/com/napzak/market/data/home/dto/ProductBuyItem.kt
  app/src/main/java/com/napzak/market/data/home/dto/ProductSellItem.kt
  app/src/main/java/com/napzak/market/data/home/mapper/HomeBuyProductMapper.kt
  app/src/main/java/com/napzak/market/data/home/mapper/HomePopularProductMapper.kt
  app/src/main/java/com/napzak/market/data/home/mapper/HomeRecommendProductMapper.kt
  app/src/main/java/com/napzak/market/data/home/repositoryImpl/HomeRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/home/service/HomeService.kt
  app/src/main/java/com/napzak/market/domain/home/model/ProductItem.kt
  app/src/main/java/com/napzak/market/domain/home/repository/HomeRepository.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeViewModel.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeItemMapper.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeItemRow.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/state/HomeUiState.kt
  app/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 석준 :melting_face:

#84 [Feat/#73] PresignedUrl API 연동
  app/src/main/java/com/napzak/market/core/network/di/NetworkModule.kt
  app/src/main/java/com/napzak/market/data/registration/datasource/RegistrationRemoteDataSource.kt
  app/src/main/java/com/napzak/market/data/registration/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/registration/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/registration/dto/PresignedUrlResponseDto.kt
  app/src/main/java/com/napzak/market/data/registration/mapper/RegistrationPresignedUrlMapper.kt
  app/src/main/java/com/napzak/market/data/registration/repositoryImpl/RegistrationRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/registration/service/RegistrationService.kt
  app/src/main/java/com/napzak/market/domain/registration/model/PresignedUrlMap.kt
  app/src/main/java/com/napzak/market/domain/registration/repository/RegistrationRepository.kt
  app/src/main/java/com/napzak/market/domain/registration/usecase/GetPresignedUrlUseCase.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationViewModel.kt
  app/src/main/java/com/napzak/market/presentation/registration/state/RegistrationUiState.kt
Labels: FEAT :sparkles:, 종명 :melting_face:

#76 [FEAT/#68] 탐색탭 팔아요/구해요(검색어X) API 연결
  app/src/main/java/com/napzak/market/data/explore/datasource/ExploreDataSource.kt
  app/src/main/java/com/napzak/market/data/explore/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/explore/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/explore/dto/ProductBuyItemsRequest.kt
  app/src/main/java/com/napzak/market/data/explore/dto/ProductBuyItemsResponse.kt
  app/src/main/java/com/napzak/market/data/explore/dto/ProductSellItemsRequest.kt
  app/src/main/java/com/napzak/market/data/explore/dto/ProductSellItemsResponse.kt
  app/src/main/java/com/napzak/market/data/explore/mapper/ExploreProductBuyItemsMapper.kt
  app/src/main/java/com/napzak/market/data/explore/mapper/ExploreProductSellItemsMapper.kt
  app/src/main/java/com/napzak/market/data/explore/repositoryimpl/ExploreRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/explore/service/ExploreService.kt
  app/src/main/java/com/napzak/market/domain/explore/model/ProductItem.kt
  app/src/main/java/com/napzak/market/domain/explore/model/ProductList.kt
  app/src/main/java/com/napzak/market/domain/explore/model/ProductListFilter.kt
  app/src/main/java/com/napzak/market/domain/explore/repository/ExploreRepository.kt
  app/src/main/java/com/napzak/market/domain/explore/usecase/GetProductBuyListUseCase.kt
  app/src/main/java/com/napzak/market/domain/explore/usecase/GetProductSellListUseCase.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketProductListSection.kt
Labels: FEAT :sparkles:, 채린 :melting_face:

#89 [FEAT/#88] 마이페이지 API 연결
  app/src/main/java/com/napzak/market/data/mypage/datasource/MyPageDataSource.kt
  app/src/main/java/com/napzak/market/data/mypage/di/MyPageRepositoryModule.kt
  app/src/main/java/com/napzak/market/data/mypage/di/MyPageServiceModule.kt
  app/src/main/java/com/napzak/market/data/mypage/dto/MyPageInfoResponse.kt
  app/src/main/java/com/napzak/market/data/mypage/repositoryImpl/MyPageRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/mypage/service/MyPageService.kt
  app/src/main/java/com/napzak/market/domain/mypage/model/StoreInfo.kt
  app/src/main/java/com/napzak/market/domain/mypage/repository/MyPageRepository.kt
  app/src/main/java/com/napzak/market/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/napzak/market/presentation/mypage/state/MyPageUiState.kt
Labels: FEAT :sparkles:, 재원 :melting_face:

#91 [FEAT/#83] 좋아요 API 연결
  app/src/main/java/com/napzak/market/core/designsystem/component/item/NapzakSellItem.kt
  app/src/main/java/com/napzak/market/core/network/NoContentBaseResponse.kt
  app/src/main/java/com/napzak/market/data/home/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/home/dto/HomeRecommendProductResponse.kt
  app/src/main/java/com/napzak/market/data/home/mapper/HomeRecommendProductMapper.kt
  app/src/main/java/com/napzak/market/data/home/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/interest/datasource/InterestDataSource.kt
  app/src/main/java/com/napzak/market/data/interest/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/interest/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/interest/repositoryimpl/InterestRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/interest/service/InterestService.kt
  app/src/main/java/com/napzak/market/domain/interest/repository/InterestRepository.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeViewModel.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeItemRow.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/res/drawable/ic_heart_unselect_24.xml
Labels: FEAT :sparkles:, 석준 :melting_face:

#92 [FEAT/#86] 온보딩 API 연결
  app/src/main/java/com/napzak/market/core/designsystem/component/GenreChipButtonGroup.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/OnboardingGenreItem.kt
  app/src/main/java/com/napzak/market/data/genre/datasource/GenreManagementDataSource.kt
  app/src/main/java/com/napzak/market/data/genre/datasource/ImageGenreDataSource.kt
  app/src/main/java/com/napzak/market/data/genre/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/genre/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/genre/dto/GenreRegisterRequest.kt
  app/src/main/java/com/napzak/market/data/genre/dto/GenreRegisterResponse.kt
  app/src/main/java/com/napzak/market/data/genre/dto/ImageGenresResponse.kt
  app/src/main/java/com/napzak/market/data/genre/mapper/GenreListMapper.kt
  app/src/main/java/com/napzak/market/data/genre/mapper/ImageGenreListMapper.kt
  app/src/main/java/com/napzak/market/data/genre/repositoryimpl/GenreManagementRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/genre/repositoryimpl/GenreRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/genre/repositoryimpl/ImageGenreRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/genre/service/GenreManagementService.kt
  app/src/main/java/com/napzak/market/data/genre/service/ImageGenreService.kt
  app/src/main/java/com/napzak/market/domain/genre/respository/GenreManagementRepository.kt
  app/src/main/java/com/napzak/market/domain/genre/respository/ImageGenreRepository.kt
  app/src/main/java/com/napzak/market/domain/genre/usecase/GenreRegisterUseCase.kt
  app/src/main/java/com/napzak/market/domain/genre/usecase/ImageGenreSearchUseCase.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingScreen.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingSideEffect.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/state/OnboardingUiState.kt
Labels: FEAT :sparkles:, 석준 :melting_face:

#93 [FEAT/#70] 상세페이지 상품상세정보 조회 API 연결 API 연결
  app/src/main/java/com/napzak/market/core/type/TradeType.kt
  app/src/main/java/com/napzak/market/data/detailpage/datasource/DetailPageDataSource.kt
  app/src/main/java/com/napzak/market/data/detailpage/di/DetailPageRepositoryModule.kt
  app/src/main/java/com/napzak/market/data/detailpage/di/DetailPageServiceModule.kt
  app/src/main/java/com/napzak/market/data/detailpage/dto/ProductDetailResponse.kt
  app/src/main/java/com/napzak/market/data/detailpage/mapper/ProductDetailResponseMapper.kt
  app/src/main/java/com/napzak/market/data/detailpage/repositoryimpl/DetailPageRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/detailpage/service/DetailPageService.kt
  app/src/main/java/com/napzak/market/domain/detailpage/model/ProductDetail.kt
  app/src/main/java/com/napzak/market/domain/detailpage/repository/DetailPageRepository.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageViewModel.kt
Labels: FEAT :sparkles:, 재원 :melting_face:

#94 [FEAT/#79] 상점조회 API 연결
  app/src/main/java/com/napzak/market/data/marketinfo/datasource/MarketInfoDataSource.kt
  app/src/main/java/com/napzak/market/data/marketinfo/di/RepositoryModule.kt
  app/src/main/java/com/napzak/market/data/marketinfo/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/GenrePreference.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/MarketInfoResponse.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/MarketProductBuyItemsRequest.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/MarketProductBuyItemsResponse.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/MarketProductSellItemsRequest.kt
  app/src/main/java/com/napzak/market/data/marketinfo/dto/MarketProductSellItemsResponse.kt
  app/src/main/java/com/napzak/market/data/marketinfo/mapper/MarketInfoMapper.kt
  app/src/main/java/com/napzak/market/data/marketinfo/mapper/MarketProductBuyItemsMapper.kt
  app/src/main/java/com/napzak/market/data/marketinfo/mapper/MarketProductSellItemsMapper.kt
  app/src/main/java/com/napzak/market/data/marketinfo/repositoryimpl/MarketInfoRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/marketinfo/service/MarketInfoService.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/model/MarketInfo.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/model/ProductItem.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/model/ProductList.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/model/ProductListFilter.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/repository/MarketInfoRepository.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/GetMarketInfoUseCase.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/GetMarketProductBuyItemsUseCase.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/GetMarketProductSellItemsUseCase.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoViewModel.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketInfoTopSection.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/state/MarketInfoUiState.kt
Labels: FEAT :sparkles:, 채린 :melting_face:

#98 [FEAT/#85] S3 버킷에 이미지 업로드 기능 구현
  app/src/main/java/com/napzak/market/core/common/util/ContentUriRequestBody.kt
  app/src/main/java/com/napzak/market/core/network/di/ContentResolverModule.kt
  app/src/main/java/com/napzak/market/data/registration/datasource/RegistrationRemoteDataSource.kt
  app/src/main/java/com/napzak/market/data/registration/di/ServiceModule.kt
  app/src/main/java/com/napzak/market/data/registration/dto/PresignedUrlResponseDto.kt
  app/src/main/java/com/napzak/market/data/registration/mapper/RegistrationPresignedUrlMapper.kt
  app/src/main/java/com/napzak/market/data/registration/repositoryImpl/RegistrationRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/registration/service/ImageRegistrationService.kt
  app/src/main/java/com/napzak/market/data/registration/service/PostRegistrationService.kt
  app/src/main/java/com/napzak/market/domain/registration/model/PresignedUrlMap.kt
  app/src/main/java/com/napzak/market/domain/registration/repository/RegistrationRepository.kt
  app/src/main/java/com/napzak/market/domain/registration/usecase/ImageUriUseCase.kt
  app/src/main/java/com/napzak/market/domain/registration/usecase/PresignedUrlUseCase.kt
  app/src/main/java/com/napzak/market/domain/registration/usecase/ProductRegistrationUseCase.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationViewModel.kt
  app/src/main/java/com/napzak/market/presentation/registration/state/RegistrationUiState.kt
Labels: FEAT :sparkles:, 종명 :melting_face:

#99 [UI/#97] 등록 dialog 위치 및 로직 수정
  app/src/main/java/com/napzak/market/presentation/main/MainNavigator.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainRegisterDialog.kt
Labels: 종명 :melting_face:, UI :iphone:

#100 [FEAT/#78] 탐색,마켓보기 장르 검색 관련 API 연결
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/domain/genre/model/Genre.kt
  app/src/main/java/com/napzak/market/domain/genre/usecase/GenreRegisterUseCase.kt
  app/src/main/java/com/napzak/market/domain/genre/usecase/GenreSearchUseCase.kt
  app/src/main/java/com/napzak/market/domain/genre/usecase/ImageGenreSearchUseCase.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/GetMarketInfoUseCase.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/MarketProductBuyItemsUseCase.kt
  app/src/main/java/com/napzak/market/domain/marketinfo/usecase/MarketProductSellItemsUseCase.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ExploreBottomSheetScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/state/ExploreUiState.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/SearchViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/component/SearchGenreListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/state/SearchUiState.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoViewModel.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketInfoBottomSheetScreen.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/state/MarketInfoUiState.kt
  app/src/main/java/com/napzak/market/presentation/onboarding/OnboardingViewModel.kt
Labels: FEAT :sparkles:, 채린 :melting_face:

#110 [ADD/#109] 앱 아이콘
  app/src/main/AndroidManifest.xml
  app/src/main/ic_napzak_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_napzak_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_napzak_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-hdpi/ic_napzak_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_napzak_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_napzak_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_napzak_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_napzak_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_napzak_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_napzak_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_napzak_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_napzak_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_napzak_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_napzak_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_napzak_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_napzak_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_napzak_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_napzak_launcher_round.webp
  app/src/main/res/values/ic_napzak_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: ADD ➕, 암살자석준 :rage:

#107 [FEAT/#95] 채팅 관련 정보 조회 API 연결
  app/build.gradle.kts
  app/src/main/java/com/napzak/market/data/chat/datasource/ChatDataSource.kt
  app/src/main/java/com/napzak/market/data/chat/di/ChatRepositoryModule.kt
  app/src/main/java/com/napzak/market/data/chat/di/ChatServiceModule.kt
  app/src/main/java/com/napzak/market/data/chat/dto/ChatInfoResponse.kt
  app/src/main/java/com/napzak/market/data/chat/mapper/ChatInfoResponseMapper.kt
  app/src/main/java/com/napzak/market/data/chat/repositoryimpl/ChatRepositoryImpl.kt
  app/src/main/java/com/napzak/market/data/chat/service/ChatService.kt
  app/src/main/java/com/napzak/market/domain/chat/model/ChatInfo.kt
  app/src/main/java/com/napzak/market/domain/chat/repository/ChatRepository.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/ChatViewModel.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/ItemChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/component/ChatInfoSection.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/navigation/ItemChatNavigation.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/type/ChatType.kt
  app/src/main/java/com/napzak/market/presentation/chat/itemchat/type/ChatUiState.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/navigation/DetailPageNavigation.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#105 [FEAT/#103] 탐색탭, 마켓보기 내 좋아요 API 연결
  app/src/main/java/com/napzak/market/data/mypage/dto/MyPageInfoResponse.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoViewModel.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketProductListSection.kt
Labels: FEAT :sparkles:, 충신채린 :saluting_face:

#115 [FIX/#101] ProductConditionType 이름 변경
  app/src/main/java/com/napzak/market/core/type/ProductConditionType.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/ProductConditionGridButton.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationSellGroup.kt
Labels: FEAT :sparkles:, 퍼시벌종명 :sunglasses:

#114 [FEAT/#112] Nav 적용 DetailPage -> MarketInfo
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/navigation/DetailPageNavigation.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
Labels: FEAT :sparkles:, 모드레드재원 :imp:

#120 [REFACTOR/#119] 탐색탭/마켓보기 UI QA
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/GenreSearchBottomSheet.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/BasicChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/chip/TextChip.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/item/GenreSearchItem.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/search/component/GenreTextChip.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#122 [REFACTOR/#118] 상세페이지(+준비중) QA
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/BackTopBar.kt
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/CommonTopBar.kt
  app/src/main/java/com/napzak/market/presentation/chat/chat/ChatScreen.kt
  app/src/main/java/com/napzak/market/presentation/chat/chat/navigation/ChatNavigation.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/prepare/PrepareScreen.kt
  app/src/main/java/com/napzak/market/presentation/prepare/navigation/chatNavigation.kt
Labels: REFACTOR :recycle:, 모드레드재원 :imp:

#125 [REFACTOR/#121] 홈 QA 반영
  app/src/main/java/com/napzak/market/core/designsystem/component/topbar/NapzakLogoTopBar.kt
  app/src/main/java/com/napzak/market/presentation/home/HomeScreen.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeBannerPager.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeMostSearchedItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomePopularItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/home/component/HomeRecommendationItemGroup.kt
  app/src/main/java/com/napzak/market/presentation/main/MainScreen.kt
  app/src/main/java/com/napzak/market/presentation/main/component/MainRegisterDialog.kt
Labels: REFACTOR :recycle:, 암살자석준 :rage:

#126 [REFACTOR/#123] 등록화면 QA 반영
  app/src/main/java/com/napzak/market/core/designsystem/component/LoadingScreen.kt
  app/src/main/java/com/napzak/market/data/registration/mapper/RegistrationProductMapper.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationViewModel.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostFeeSelector.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/RegistrationSellGroup.kt
  app/src/main/java/com/napzak/market/presentation/registration/state/RegistrationContract.kt
Labels: REFACTOR :recycle:, 퍼시벌종명 :sunglasses:

#128 [REFACTOR/#124] 탐색탭 내 장르 바텀시트 오류 해결
  app/src/main/java/com/napzak/market/core/designsystem/component/bottomSheet/GenreSearchBottomSheet.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#133 [FIX/#129] 내 마켓 보기 버튼 디자인 수정
  app/src/main/java/com/napzak/market/presentation/mypage/MyPageScreen.kt
Labels: FIX :hammer:, 모드레드재원 :imp:

#135 [REFACTOR/#131] qa2 explore view
  app/src/main/java/com/napzak/market/core/designsystem/component/GenreChipButtonGroup.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/ProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/component/TradeTypeTab.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/MarketInfoRoute.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketGenreChip.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketProductListSection.kt
  app/src/main/java/com/napzak/market/presentation/marketinfo/component/MarketTradeTypeTab.kt
Labels: REFACTOR :recycle:, 충신채린 :saluting_face:

#138 [FIX/#130] 등록 최최최최종 QA 반영
  app/src/main/java/com/napzak/market/core/designsystem/component/LoadingScreen.kt
  app/src/main/java/com/napzak/market/data/registration/mapper/RegistrationProductMapper.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationScreen.kt
  app/src/main/java/com/napzak/market/presentation/registration/RegistrationViewModel.kt
  app/src/main/java/com/napzak/market/presentation/registration/component/PostOptionCard.kt
Labels: FIX :hammer:, 퍼시벌종명 :sunglasses:

#132 [FIX/#127] 탐색화면 상태관리 수정
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreScreen.kt
  app/src/main/java/com/napzak/market/presentation/explore/explore/ExploreViewModel.kt
Labels: FIX :hammer:, 암살자석준 :rage:

#140 [FIX/#139] 상세페이지 구해요 수정(Chip, '~원대')
  app/src/main/java/com/napzak/market/presentation/detailpage/DetailPageScreen.kt
  app/src/main/java/com/napzak/market/presentation/detailpage/component/ProductInfoSection.kt
Labels: FIX :hammer:, 모드레드재원 :imp:
